name: Bug Report
description: Report a bug / crash
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.
        
  - type: input
    id: class-builder-generator-version
    attributes:
      label: ClassBuilderGenerator version
      description: |
        You can find the version of the extension in the extensions screen.
      placeholder: "1.5.5"
    validations:
      required: true
      
  - type: input
    id: windows-version
    attributes:
      label: Windows Version
      placeholder: "10"
    validations:
      required: true
      
  - type: input
    id: visual-studio-version
    attributes:
      label: Visual Studio Version
      description: |
        You can get this from the about screen.
      placeholder: "2022 17.0.0"
    validations:
      required: true
      
  - type: dropdown
    id: other-extensions
    validations:
        required: true
    attributes:
      label: Do you have other extensions installed?
      description: |
        If you have other extensions installed, please add to in the extra info box at the end.
      multiple: false
      options:
        - 'Yes'
        - 'No'
        
  - type: input
    id: bug-description
    attributes:
      label: Describe the issue
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
      
  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Open Visual Studio...
        2. Create a class...
        3. Right click...
    validations:
      required: true
      
  - type: input
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: "Link(s) to any log files that you can provide"
      placeholder: |
        https://pste.ch/ihaveaproble
        https://pastebin.com/
        https://paste.feed-the-beast.com/
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
