name: ClassBuilderGenerator PR Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: "Build for PR"
    runs-on: ${{ matrix.os }}
    
    env:
      DOTNET_NOLOGO: true
      
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        config: [Debug, Release]
        
    steps:
      - name: Clone source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK (v2.1)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '2.1.818'
          
      - name: Setup .NET SDK (v3.1)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.414'
          
      - name: Setup .NET SDK (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.402'
          
      - name: Setup .NET SDK (v6.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.202'

      - name: Get .NET information
        run: dotnet --info
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c ${{ matrix.config }} --no-restore
      
      - name: "Test"
        run: dotnet test -c ${{ matrix.config }}
