name: Class Builder Generator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_VERSION: 6.0.202

jobs:
  build:
    name: "Build for PR"
    runs-on: ${{ matrix.os }}
    
    env:
      DOTNET_NOLOGO: true
      
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        config: [Release]
        
    steps:
      - name: Clone source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get .NET information
        run: dotnet --info
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c ${{ matrix.config }} --no-restore
      
      - name: "Test"
        run: dotnet test -c ${{ matrix.config }}
